### ISSUE TITLE
brunch_version check error

### ISSUE THREAD

**Issue by DennisLfromGA** [WesBosch/Brunch-Updater#3]
The `/etc/brunch_version` check, [currently on line74](https://github.com/WesBosch/Brunch-Updater/blob/master/brunch-toolkit.sh#L74
), still throws an error if it's missing.

To avoid it I think it might need to change -
From: `CURRENT=$(awk '{print $4}' < /etc/brunch_version 2> /dev/null)`
To ...: `CURRENT=$(awk '{print $4}' 2> /dev/null < /etc/brunch_version)`

I *can* make a pull request if you'd prefer but I wasn't sure it was necessary for this minor change - if you want to do it.

**Comment by WesBosch** [comment]
Oh, thank you! I assume this error is only encountered when using linux
instead of brunch? It is a minor enough change, so I'll add it manually
when I get home tonight

**Comment by DennisLfromGA** [comment]
> I assume this error is only encountered when using linux
instead of brunch?

Yep, that seems to be the case. I discovered it on my Pixelbook running Chrome OS.
